language: node_js
sudo: required
#addons:
#  chrome: stable
node_js:
  - 10
os: linux
cache:
  yarn: true
branches:
  only:
    - master
install:
  - |
    yarn install
  - |
    npm run lint && npm run test
script:
  - ./build/release-site.sh
after_success:
  - |
    cat ./test/coverage/lcov.info | ./node_modules/.bin/codecov
deploy:
  - provider: pages
    local-dir: docs/dist
    github-token: $GITHUB_TOKEN
    skip-cleanup: true
